/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  color?: "indigo" | "blue" | "green" | "red" | "orange" | "purple" | "pink";
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  readTime?: number;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  author?: AuthorReference;
  relatedPosts?: Array<
    {
      _key: string;
    } & PostReference
  >;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        title?: string;
        subtitle?: string;
        buttonText?: string;
        buttonUrl?: string;
        style?: "indigo" | "dark";
        _type: "callToAction";
        _key: string;
      }
    | {
        language?:
          | "javascript"
          | "typescript"
          | "tsx"
          | "css"
          | "bash"
          | "json"
          | "python"
          | "sql";
        filename?: string;
        code?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        url?: string;
        caption?: string;
        _type: "youtubeEmbed";
        _key: string;
      }
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  bio?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  twitter?: string;
  linkedin?: string;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  navCtaText?: string;
  heroTitle?: string;
  heroSubtitle?: string;
  heroCtaText?: string;
  heroCtaLink?: string;
  heroDashboardImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  logosTitle?: string;
  logos?: Array<{
    name?: string;
    logo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  featuresTitle?: string;
  featuresSubtitle?: string;
  features?: Array<{
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  statsTitle?: string;
  stats?: Array<{
    number?: string;
    label?: string;
    _key: string;
  }>;
  testimonialsTitle?: string;
  testimonials?: Array<{
    quote?: string;
    authorName?: string;
    authorRole?: string;
    authorAvatar?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _key: string;
  }>;
  ctaTitle?: string;
  ctaSubtitle?: string;
  ctaButtonText?: string;
  ctaButtonLink?: string;
  footerCopyright?: string;
  howItWorksTitle?: string;
  howItWorksSubtitle?: string;
  howItWorksSteps?: Array<{
    step?: number;
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  pricingTitle?: string;
  pricingSubtitle?: string;
  pricingPlans?: Array<{
    name?: string;
    price?: string;
    period?: string;
    description?: string;
    features?: Array<string>;
    ctaText?: string;
    ctaLink?: string;
    highlighted?: boolean;
    _key: string;
  }>;
  trustTitle?: string;
  trustSubtitle?: string;
  trustBadges?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  tagline?: string;
  navLinks?: Array<{
    label?: string;
    href?: string;
    openInNewTab?: boolean;
    _key: string;
  }>;
  navCtaText?: string;
  navCtaLink?: string;
  footerText?: string;
  socialLinks?: {
    twitter?: string;
    linkedin?: string;
    github?: string;
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Tag
  | Slug
  | SanityImageAssetReference
  | TagReference
  | AuthorReference
  | PostReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Homepage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/homepage.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0] {    _id,    logo { asset, alt },    navCtaText,    heroTitle,    heroSubtitle,    heroCtaText,    heroCtaLink,    heroDashboardImage { asset, alt },    logosTitle,    logos[] {      _key,      name,      logo { asset, alt }    },    featuresTitle,    featuresSubtitle,    features[] {      _key,      title,      description,      image { asset, alt }    },    statsTitle,    stats[] { _key, number, label },    testimonialsTitle,    testimonials[] {      _key,      quote,      authorName,      authorRole,      authorAvatar { asset, alt }    },    ctaTitle,    ctaSubtitle,    ctaButtonText,    ctaButtonLink,    footerCopyright,    howItWorksTitle,    howItWorksSubtitle,    howItWorksSteps[] { _key, step, icon, title, description },    pricingTitle,    pricingSubtitle,    pricingPlans[] {      _key, name, price, period, description,      features,      ctaText, ctaLink, highlighted    },    trustTitle,    trustSubtitle,    trustBadges[] { _key, icon, title, description },    seo {      metaTitle,      metaDescription,      ogImage { asset }    }  }
export type HOMEPAGE_QUERY_RESULT = {
  _id: string;
  logo: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  navCtaText: string | null;
  heroTitle: string | null;
  heroSubtitle: string | null;
  heroCtaText: string | null;
  heroCtaLink: string | null;
  heroDashboardImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  logosTitle: string | null;
  logos: Array<{
    _key: string;
    name: string | null;
    logo: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  }> | null;
  featuresTitle: string | null;
  featuresSubtitle: string | null;
  features: Array<{
    _key: string;
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  }> | null;
  statsTitle: string | null;
  stats: Array<{
    _key: string;
    number: string | null;
    label: string | null;
  }> | null;
  testimonialsTitle: string | null;
  testimonials: Array<{
    _key: string;
    quote: string | null;
    authorName: string | null;
    authorRole: string | null;
    authorAvatar: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  }> | null;
  ctaTitle: string | null;
  ctaSubtitle: string | null;
  ctaButtonText: string | null;
  ctaButtonLink: string | null;
  footerCopyright: string | null;
  howItWorksTitle: string | null;
  howItWorksSubtitle: string | null;
  howItWorksSteps: Array<{
    _key: string;
    step: number | null;
    icon: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  pricingTitle: string | null;
  pricingSubtitle: string | null;
  pricingPlans: Array<{
    _key: string;
    name: string | null;
    price: string | null;
    period: string | null;
    description: string | null;
    features: Array<string> | null;
    ctaText: string | null;
    ctaLink: string | null;
    highlighted: boolean | null;
  }> | null;
  trustTitle: string | null;
  trustSubtitle: string | null;
  trustBadges: Array<{
    _key: string;
    icon: string | null;
    title: string | null;
    description: string | null;
  }> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: SanityImageAssetReference | null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/posts.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    coverImage { asset, alt },    publishedAt,    readTime,    tags[]-> {      _id,      name,      "slug": slug.current,      color    },    author-> {      _id,      name,      role,      avatar { asset, alt }    }  }
export type ALL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  readTime: number | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    color:
      | "blue"
      | "green"
      | "indigo"
      | "orange"
      | "pink"
      | "purple"
      | "red"
      | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    avatar: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  } | null;
}>;

// Source: sanity/queries/posts.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    excerpt,    coverImage { asset, alt },    publishedAt,    readTime,    tags[]-> {      _id,      name,      "slug": slug.current,      color    },    author-> {      _id,      name,      role,      bio,      avatar { asset, alt },      twitter,      linkedin    },    body[] {      ...,      _type == "image" => {        ...,        asset      }    },    seo {      metaTitle,      metaDescription,      ogImage { asset }    },    relatedPosts[]-> {      _id,      title,      "slug": slug.current,      excerpt,      coverImage { asset, alt },      publishedAt,      readTime,      author-> { name, avatar { asset, alt } }    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  readTime: number | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    color:
      | "blue"
      | "green"
      | "indigo"
      | "orange"
      | "pink"
      | "purple"
      | "red"
      | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    bio: string | null;
    avatar: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
    twitter: string | null;
    linkedin: string | null;
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        title?: string;
        subtitle?: string;
        buttonText?: string;
        buttonUrl?: string;
        style?: "dark" | "indigo";
        _type: "callToAction";
        _key: string;
      }
    | {
        language?:
          | "bash"
          | "css"
          | "javascript"
          | "json"
          | "python"
          | "sql"
          | "tsx"
          | "typescript";
        filename?: string;
        code?: string;
        _type: "codeBlock";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        url?: string;
        caption?: string;
        _type: "youtubeEmbed";
        _key: string;
      }
  > | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset: SanityImageAssetReference | null;
    } | null;
  } | null;
  relatedPosts: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    excerpt: string | null;
    coverImage: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
    publishedAt: string | null;
    readTime: number | null;
    author: {
      name: string | null;
      avatar: {
        asset: SanityImageAssetReference | null;
        alt: string | null;
      } | null;
    } | null;
  }> | null;
} | null;

// Source: sanity/queries/posts.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)] {    "slug": slug.current  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _id,    siteName,    tagline,    navCtaText,    navCtaLink,    navLinks[] { _key, label, href, openInNewTab },    footerText,    socialLinks { twitter, linkedin, github }  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  siteName: string | null;
  tagline: string | null;
  navCtaText: string | null;
  navCtaLink: string | null;
  navLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
    openInNewTab: boolean | null;
  }> | null;
  footerText: string | null;
  socialLinks: {
    twitter: string | null;
    linkedin: string | null;
    github: string | null;
  } | null;
} | null;

// Source: sanity/queries/tags.ts
// Variable: ALL_TAGS_QUERY
// Query: *[_type == "tag"] | order(name asc) {    _id,    name,    "slug": slug.current,    description,    color  }
export type ALL_TAGS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  color:
    | "blue"
    | "green"
    | "indigo"
    | "orange"
    | "pink"
    | "purple"
    | "red"
    | null;
}>;

// Source: sanity/queries/tags.ts
// Variable: TAG_QUERY
// Query: *[_type == "tag" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    description,    color  }
export type TAG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  color:
    | "blue"
    | "green"
    | "indigo"
    | "orange"
    | "pink"
    | "purple"
    | "red"
    | null;
} | null;

// Source: sanity/queries/tags.ts
// Variable: TAG_SLUGS_QUERY
// Query: *[_type == "tag" && defined(slug.current)] {    "slug": slug.current  }
export type TAG_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/queries/tags.ts
// Variable: POSTS_BY_TAG_QUERY
// Query: *[_type == "post" && $tagId in tags[]._ref] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    excerpt,    coverImage { asset, alt },    publishedAt,    readTime,    tags[]-> {      _id,      name,      "slug": slug.current,      color    },    author-> {      _id,      name,      role,      avatar { asset, alt }    }  }
export type POSTS_BY_TAG_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
  } | null;
  publishedAt: string | null;
  readTime: number | null;
  tags: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    color:
      | "blue"
      | "green"
      | "indigo"
      | "orange"
      | "pink"
      | "purple"
      | "red"
      | null;
  }> | null;
  author: {
    _id: string;
    name: string | null;
    role: string | null;
    avatar: {
      asset: SanityImageAssetReference | null;
      alt: string | null;
    } | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "homepage"][0] {\n    _id,\n    logo { asset, alt },\n    navCtaText,\n    heroTitle,\n    heroSubtitle,\n    heroCtaText,\n    heroCtaLink,\n    heroDashboardImage { asset, alt },\n    logosTitle,\n    logos[] {\n      _key,\n      name,\n      logo { asset, alt }\n    },\n    featuresTitle,\n    featuresSubtitle,\n    features[] {\n      _key,\n      title,\n      description,\n      image { asset, alt }\n    },\n    statsTitle,\n    stats[] { _key, number, label },\n    testimonialsTitle,\n    testimonials[] {\n      _key,\n      quote,\n      authorName,\n      authorRole,\n      authorAvatar { asset, alt }\n    },\n    ctaTitle,\n    ctaSubtitle,\n    ctaButtonText,\n    ctaButtonLink,\n    footerCopyright,\n    howItWorksTitle,\n    howItWorksSubtitle,\n    howItWorksSteps[] { _key, step, icon, title, description },\n    pricingTitle,\n    pricingSubtitle,\n    pricingPlans[] {\n      _key, name, price, period, description,\n      features,\n      ctaText, ctaLink, highlighted\n    },\n    trustTitle,\n    trustSubtitle,\n    trustBadges[] { _key, icon, title, description },\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage { asset }\n    }\n  }\n': HOMEPAGE_QUERY_RESULT;
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage { asset, alt },\n    publishedAt,\n    readTime,\n    tags[]-> {\n      _id,\n      name,\n      "slug": slug.current,\n      color\n    },\n    author-> {\n      _id,\n      name,\n      role,\n      avatar { asset, alt }\n    }\n  }\n': ALL_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage { asset, alt },\n    publishedAt,\n    readTime,\n    tags[]-> {\n      _id,\n      name,\n      "slug": slug.current,\n      color\n    },\n    author-> {\n      _id,\n      name,\n      role,\n      bio,\n      avatar { asset, alt },\n      twitter,\n      linkedin\n    },\n    body[] {\n      ...,\n      _type == "image" => {\n        ...,\n        asset\n      }\n    },\n    seo {\n      metaTitle,\n      metaDescription,\n      ogImage { asset }\n    },\n    relatedPosts[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      excerpt,\n      coverImage { asset, alt },\n      publishedAt,\n      readTime,\n      author-> { name, avatar { asset, alt } }\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    _id,\n    siteName,\n    tagline,\n    navCtaText,\n    navCtaLink,\n    navLinks[] { _key, label, href, openInNewTab },\n    footerText,\n    socialLinks { twitter, linkedin, github }\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "tag"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    color\n  }\n': ALL_TAGS_QUERY_RESULT;
    '\n  *[_type == "tag" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    color\n  }\n': TAG_QUERY_RESULT;
    '\n  *[_type == "tag" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': TAG_SLUGS_QUERY_RESULT;
    '\n  *[_type == "post" && $tagId in tags[]._ref] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    coverImage { asset, alt },\n    publishedAt,\n    readTime,\n    tags[]-> {\n      _id,\n      name,\n      "slug": slug.current,\n      color\n    },\n    author-> {\n      _id,\n      name,\n      role,\n      avatar { asset, alt }\n    }\n  }\n': POSTS_BY_TAG_QUERY_RESULT;
  }
}
